### ISSUE TITLE
pimctl

### ISSUE THREAD

**Issue by Kzibi** [troglobit/pimd#144]
pimd is running with ident  pimd_jambox[

1. pimctl restart leave untouched socket, so after that pimctl is not working (pimd is working fine with new pid)

2. pimctl log debug ; 
         pimd_jambox: Setting new log level debug
   pimctl debug pim_jp 
nothing is logging , but tcpdump show pim join/prune packets
with more debug options, pim report : 
        pimd_jambox: logging too fast, shutting up for 10 minutes
        pimd_jambox: logging enabled again after rate limiting

**Comment by troglobit** [comment]
I'm guessing this is the latest master sources?  You should know, first of all, that this is still in development and not considered stable.

Now, I'm aware of several problems with the current implementation of debug.c:logit().  In fact, the whole thing should probably be refactored completely before the 3.0 release.  However, in the meantime, what you can try is run `pimd -n`, i.e. in the foreground, to get all logs to stdout/stderr instead.  That should help your debugging efforts.

**Comment by troglobit** [comment]
OK, I've looked into this now.  It turns out not even the original sources had any sub-system scoping for join/prune messages, or even any relevant log messages -- so not implemented ... almost. We "recently" added log messages for join/prune, but they're not scoped (yet).  Available from loglevel `LOG_INFO`.

I will take the opportunity to introduce sub-system scoping of these new log messages right now.  So it will be made available as intended very soon.
