### ISSUE TITLE
Running on Ubuntu viritual machine on VLANx

### ISSUE THREAD

**Issue by Nauticno** [troglobit/pimd#154]
Hi!
I am new to this! I run pimd on a viritual Ubuntu machine connected to VLANx on ens192. I run IPTV's on this. When I debug I see this:

Received IGMP v3 Membership Report from xxx.xxx.xxx.12 to 224.0.0.22

When I run  $ sudo pimd -r
I see no line for  sudo pimd -r

When running
$ sudo pimd --debug=interface

I get 
Installing ens192 (xxx.xxxx.xxx.114 on subnet 192.168.9) as vif #0-2 - rate 0

Do I have to define my VLAN9 in /etc/pimd.conf ?

Best regards
Nautic

**Comment by troglobit** [comment]
Hi,

to answer your question, without knowing anything about your network setup or your problem, it depends. What are you trying to accomplish, and what issue have you found with pimd?

**Comment by Nauticno** [comment]
Hi!
I am using Unifi USG-PRO-4 as router and igmp-proxy app. Unifi do not support igmp and therfore no fix of my problem. I found this software and try to get it to work outside router. Perhaps it is not possible?

**Comment by troglobit** [comment]
Maybe you could tell me a bit more about what problem you are trying to solve and, more importantly, how pimd is malfunctioning since you've reported an issue with the project.

**Comment by Nauticno** [comment]
Sorry for missposting! Is pimd designed for routers only?

**Comment by troglobit** [comment]
Any UNIX machine can be a router.

What is the problem you want to solve, and what is the issue you've run into with pimd?  Without details about your setup and what you want to do I cannot help you.

If you are new to IP multicast then have a look at these resources first to educate yourself on the subject, there are of course many gotchas and things to learn, but they should help you get started at least:

- https://en.wikipedia.org/wiki/IP_multicast
- https://troglobit.com/howto/multicast/

Just remember, issue trackers are for reporting bugs and feature requests, not for seeking help or education on matter subjects.

**Comment by Nauticno** [comment]
I have problems with glitches on my IPTV system. This can be something in my USG-PRO-4. Thats why I try tp get this to work.
I get:

-  Received IGMP v3 Membership Report from 192.168.xxx.xx to 224.0.0.22
- accept_membership_report(): IGMP v3 report, 24 bytes, from 192.168.xxx.xx to 224.0.0.22 with 2 group records.
- Set delete timer for group: 233.184.49.10
- SM group order from  192.168.xxx.xx (*,233.184.49.10)
- Set delete timer for group: 224.0.0.2
- Not creating routing entry for LAN scoped group 224.0.0.2
And this is spinning
Looks like it should work. But pimd -r show no routes.

**Comment by troglobit** [comment]
OK, three things:

1. The range of multicast groups 224.0.0.0 - 224.0.0.255 are reserved for protocols and should never be routed.  The debug text in pimd regarding these addresses should be fixed, but that's not the issue here I'm sure.
2. The group 233.184.49.10 looks more interesting, and is possibly the group used by your IPTV system
3. Use `tcpdump -vvv` or Wireshark to inspect the multcast stream for 233.184.49.10.  The IP TTL value must be > 1 for the traffic to be routed.  If the TTL is 1 (or lower?) pimd will not consider it for routing.

I'm still confused about your actual setup/topology.   Since you're attempting to use pimd, I'm guessing you have at least two LANs and you want to route multicast between them?  For this to work the multicast stream must be readily available to the router running pimd, because it does not send any IGMP join for multicast groups on the sender LAN.  On the receiver side it is important that pimd hear the IGMP join from the receiver, otherwise it will not consider the group for routing.

> Tip: In many cases for home networks, people end up using igmpproxy or mcproxy instead of pimd.

**Comment by Nauticno** [comment]
Hi!
igmpproxy are running on my router.  I found this:
https://www.reddit.com/r/UNIFI/comments/e1dpl6/sonos_igmp_proxy_suddenly_broken/
as you see igmpproxy are broken. I now has installed pimd on my router. It is pimd version 2.1.8.
I have diabled all phyint except phyint eth0.9  That is VLAN where my IPTV boxes lives
I am getting Cache miss, src 192.168.xxx.xx, dst 239.255.255.250, iif 4. 

On my home network igmpproxy is not 100% stable. I hope to get pimd stable!

**Comment by troglobit** [comment]
Well, they are not interchangable, so just replacing igmpproxy with pimd is not guaranteed to work. Also, pimd requires at least two interfaces enabled to operate.

I'm not sure I can help you any further.

**Comment by Nauticno** [comment]
Do you have any tips for  Cache miss ?

**Comment by troglobit** [comment]
A cache miss is when incoming multicast traffic does not match a multicast route.  

Closing this issue now, since there's nothing in here that's a bug or feature request with pimd.  I cannot spend my free time to educate you on multicast routing or the PIM RFC.

**Comment by Nauticno** [comment]
Thank you VERY MUCH for your time! Can you recomend a forum for pimd?
