### ISSUE TITLE
Question:the hello-interval can be less than 30s?Does the pimd protocol can support vxworks operating system?

### ISSUE THREAD

**Issue by zcauto** [troglobit/pimd#213]
I have two questions.
1. From the pimd.conf file, we can see that the hello-interval should be less than 30s. Is there any problem if I set the hello-interval to 5s?
2. Does PIMD protocol support vxworks operating system? I see that the code of the PIMD protocol uses “netlink”, which is unique to LINUX!

**Comment by troglobit** [comment]
0. There's a Discussions tab for questions.  Issues are for actual bugs/feature requests.
 1. The pimd.conf says *Don't* set lower than 30.  I guess you forgot the critical keyword 'not' somewhere.  Anyway, the problem is twofold: a) internal timers which everything is built around have a smallest resolution of 5 sec, 2) there are lots of things that are triggered by a new hello interval which in turn can severely impact CPU load an reliability
 2. The pimd implementation is born in a UNIX world, and started out using BSD routing sockets to query the unicast routing table, later Linux netlink support was also added. The list of supported operating systems are listed in the README, and as you can see VxWorks is not listed there.  However, last I checked, VxWorks had a NetBSD derived networking stack so it should be possible in theory to port it to VxWorks, even though I wouldn't recommend it.
