### ISSUE TITLE
pimd-2.3.0-dev: *** No rule to make target `libite/strlcpy.o', needed by `pimd'.  - SOLVED

### ISSUE THREAD

**Issue by HubertMa** [troglobit/pimd#52]
libite-1.0.0 installed. Looks OK, though
 tempfile.c:25:2: warning: #warning O_TMPFILE missing on your system, tempfile() may not work! [-Wcpp]

Now I want to make pimd-2.3.0-dev and it breaks with
*** No rule to make target `libite/strlcpy.o', needed by `pimd'.

**Comment by HubertMa** [comment]
I had to manually add the path to strlcpy.o, pidfile.o and strtonum.o in config.mk because they are not in the same path as pimd.

**Comment by troglobit** [comment]
Hi @HubertMa, you don't need to install libite ... all you need to do is run the configure script.  It sets up the paths and build flags for your target.

    ./configure && make

That should work.   I'm testing this out on both OpenBSD 5.7 and Ubuntu Linux 14.04 LTS, and it works there. What system do you have?

**Comment by troglobit** [comment]
Seriously, since my last post I've now also tested building on Debian Jessie. Without a hitch.

What did you do to get that build error?

**Comment by HubertMa** [comment]
I first downloaded pimd-2.3.0-dev from github on my desktop PC, unzipped it, tared it and transferred to my wlan router running debian 7.1 in a very "downstripped" fashion (low memory, no unnecessary software).
make told me about missing libite stuff, so I did the same trick for libite-1.0.0. 
After that I tried again to make pimd and this brought up the above error.

**Comment by troglobit** [comment]
OK. 

First of all, you may be better off running an official release rather than bleeding edge master :wink: 
Official releases are available here https://github.com/troglobit/pimd/releases or at my FTP ftp://ftp.troglobit.com/pimd/ ... since you downloaded it yesterday I've done several bug fixes, and it's not complete yet.  That's just a word of caution.

Secondly, I'm very glad you figured out how to make it build for you!  I wish you the best of luck! :smiley:

Third, I will try to make it clearer in the GitHub interface how to use (download and build) the software.  I've never been a fan of GitHub's automated download links ...

**Comment by HubertMa** [comment]
Thank you, I'll go for V 2.2.1.
